### ISSUE TITLE
PCBNew bug on Mac OSX

### ISSUE THREAD

**Issue by fcarlier** [lachlanA/eagle-to-kicad#6]
With my pcbnew 4.0.0-rc2-1 on Mac OSX : 
I have this error message : 
Error loading board.
IO_ERROR: Unknown file type
from /Users/jenkins/remoteroot/workspace/KiCadBuildMac4/kicad/pcbnew/legacy_plugin.cpp : checkVersion() : line 570

**Comment by fcarlier** [comment]
idem with pcbnew 4.0.1 ;)

**Comment by lachlanA** [comment]
Can you send me the file ?
My email is laudas1@gmail.com

So I can check,   I only have linux,  but will give it a try,

Lachlan.

**Comment by lachlanA** [comment]
Hi fcarlier

Just double check, that in pcbnew  when opening the eagle file that you
select the  "eagle 6.x XML PCB files".brd   format.
It's confusing, I know,   that KiCad used the  "*.brd"  file type for  it's old board's which is the same
as Eagle file type,  plus adding to the confusing,   kicad only understands   eagle file's with 6.xx or above(XML format).
Where as my script understands Eagle's old binary format as well as the  new format.

So that's why the script put's the Eagle file's  into 3 target directory's.
    TARGET_DIRECTORY
     eagle_original_files/   .......................   This the copy of the Original eagle files, you picked,  so they will be exactly the same.
                                                               maybe old format.
     kicad_files->modified_eagle_files/  ....   This contains the Eagle file's converted to 6.xx format (XML format) and the molded, The script
                                                              make's those file's, to make life a little easy for finding error's and get around some of the limitations
                                                              of KiCad.   They will be the newer Eagle format,  and you need to select the Eagle PCB file from here.
                                                              not from the "eagle_original_files/" directory.   Note you have to select the  "6.xx or above(XML format)"
                                                              When opening the file in pcbnew,  from  kicad_files->modified_eagle_files/

I'ts a pity I can't scrip this, but  pcbnew dose not allow me to load a Eagle PCB file, from the command line!

I should fix the video,   to make it easier to understand, but I'm working on the KiCad side of thing's at the moment.
As it still dose some nasty thing's like,   re-sizing tracks with out warning you!,  etc..

Lachlan

**Comment by fcarlier** [comment]
Hello,

I'm using well the *.brd of modified_eagle_file ;)

I think that it's a bug of Kicad on MacOSX. kicad can't maybe detected
the eagle file ! and call directly legacy_plugin.cpp !!

If you look the source file, you can see that it need the 'PCBNEW-BOARD
Version 1' parameter and more.

I go to wait this information on this topic
https://bugs.launchpad.net/kicad/+bug/1526046

THX

**Comment by lachlanA** [comment]
Ok no problem's    sorry I don't have a Mac to test stuff out on !
I could be of more help..  

Lachlan.

**Comment by dgramop** [comment]
..?

**Comment by dgramop** [comment]
So what happened to this?

**Comment by lachlanA** [comment]
Don't no BrainyBrian,  did not get any files from  fcarlier,  and I don't have access to a mac for testing.
so have no more info to give you.

Lachlan

**Comment by cyoung** [comment]
I'm getting this error on a .brd file directly saved from Eagle 7.5.0.

**Comment by lachlanA** [comment]
Hi cyoung,  are you running the script on a Mac ?
is it only 7.5.0 ?    and is it the modified converted eagle .brd file build  by the script,  or the original file ?
Oh one last one can you sent me the file sch/pcb files  ?

Lachlan

**Comment by cyoung** [comment]
@lachlanA - yes, on macOS. I've found this bug: https://bugs.launchpad.net/kicad/+bug/1551628

It's just a KiCad interface bug for macOS. I got around it by sending the file to a Windows machine and doing the conversion there, then sending it back. It has been fixed in KiCad but I guess the fix hasn't made it to release yet.

**Comment by lachlanA** [comment]
Thanks for the info cyoung !
I think there working on a new stable version  to come out in a few weeks...
with luck it may be fixed then.

Lachlan

**Comment by coddingtonbear** [comment]
For what it's worth, you can work around this problem by installing the latest Kicad nightly development build (on the bottom of their [normal download page](http://kicad-pcb.org/download/osx/)), and then using the "Import Non Kicad Board File" menu item.

**Comment by lachlanA** [comment]
Thanks for the info Coddingtobear, 
I don't have a mac to test,  but I'm sure it will help some one else with a mac.

Lachlan
